import demo from "./assets/dishes/dish1.png";

export const productData: Product[] = [
	{
		img: demo,
		rate: 885,
		quantity: 1,
		name: "Quinoa salad",
		id: "ccdd7623-f5c4-43b6-bb17-88ccc6f1dc60",
		rating: "4.3",
		tags: ["Biriyani"],
		veg: true,
	},
	{
		img: demo,
		rate: 617,
		quantity: 1,
		name: "Seitan steak",
		id: "83ee377c-b3cb-4671-a599-4dd8dee27373",
		rating: "4.6",
		tags: ["Noodles"],
		veg: true,
	},
	{
		img: demo,
		rate: 939,
		quantity: 1,
		name: "Gluten-free pasta",
		id: "8d1fd0b3-3157-42d2-9c00-77ece9643fc7",
		rating: "2.6",
		tags: ["Fast Food items"],
		veg: true,
	},
	{
		img: demo,
		rate: 708,
		quantity: 1,
		name: "Mushroom risotto",
		id: "dd4553f3-8e93-4156-bfd2-e3928b285659",
		rating: "3.8",
		tags: ["Noodles"],
		veg: true,
	},
	{
		img: demo,
		rate: 913,
		quantity: 1,
		name: "Vegan pizza",
		id: "bff509c5-fe30-4dbf-9809-f878e4f959ce",
		rating: "2.1",
		tags: ["Fast Food items"],
		veg: true,
	},
	{
		img: demo,
		rate: 675,
		quantity: 1,
		name: "Avocado Toast",
		id: "1a2b3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6",
		rating: "4.8",
		tags: ["Meals"],
		veg: false,
	},
	{
		img: demo,
		rate: 790,
		quantity: 1,
		name: "Berry Smoothie",
		id: "1q2w3e4r-5t6y-7u8i-9o0p-a1s2d3f4g5h6",
		rating: "4.9",
		tags: ["Fast Food items"],
		veg: true,
	},
	{
		img: demo,
		rate: 850,
		quantity: 1,
		name: "Coconut Curry",
		id: "z1x2c3v4-b5n6-m7n8-l9k8-j7h6g5f4d3s2",
		rating: "4.5",
		tags: ["Meals"],
		veg: false,
	},
	{
		img: demo,
		rate: 620,
		quantity: 1,
		name: "Peanut Butter Pancakes",
		id: "0p9o8i7u-6y5t-4r3e-2w1q-a1s2d3f4g5h6",
		rating: "3.9",
		tags: ["Egg Items"],
		veg: true,
	},
	{
		img: demo,
		rate: 555,
		quantity: 1,
		name: "Zucchini Noodles",
		id: "m1n2b3v4-c5x6-z7a8-s9d8-f7g6h5j4k3l2",
		rating: "4.2",
		tags: ["Noodles"],
		veg: true,
	},
	{
		img: demo,
		rate: 475,
		quantity: 1,
		name: "Chocolate Lava Cake",
		id: "uuid-001",
		rating: "4.7",
		tags: ["Cake"],
		veg: false,
	},
	{
		img: demo,
		rate: 580,
		quantity: 1,
		name: "Omelette du Fromage",
		id: "uuid-002",
		rating: "4.5",
		tags: ["Egg Items"],
		veg: false,
	},
	{
		img: demo,
		rate: 690,
		quantity: 1,
		name: "Cheeseburger",
		id: "uuid-003",
		rating: "4.2",
		tags: ["Fast Food items"],
		veg: false,
	},
	{
		img: demo,
		rate: 805,
		quantity: 1,
		name: "Grilled Salmon",
		id: "uuid-004",
		rating: "4.8",
		tags: ["Meals"],
		veg: false,
	},
	{
		img: demo,
		rate: 865,
		quantity: 1,
		name: "Hyderabadi Biryani",
		id: "uuid-005",
		rating: "4.9",
		tags: ["Biriyani"],
		veg: false,
	},
	{
		img: demo,
		rate: 625,
		quantity: 1,
		name: "Pad Thai",
		id: "uuid-006",
		rating: "4.3",
		tags: ["Noodles"],
		veg: true,
	},
	{
		img: demo,
		rate: 740,
		quantity: 1,
		name: "Egg Fried Rice",
		id: "uuid-007",
		rating: "4.1",
		tags: ["Fried Rice"],
		veg: false,
	},
	{
		img: demo,
		rate: 490,
		quantity: 1,
		name: "Red Velvet Cupcake",
		id: "uuid-008",
		rating: "4.6",
		tags: ["Cake"],
		veg: false,
	},
	{
		img: demo,
		rate: 520,
		quantity: 1,
		name: "Scrambled Eggs",
		id: "uuid-009",
		rating: "4.0",
		tags: ["Egg Items"],
		veg: false,
	},
	{
		img: demo,
		rate: 775,
		quantity: 1,
		name: "Fish and Chips",
		id: "uuid-010",
		rating: "3.8",
		tags: ["Fast Food items"],
		veg: false,
	},
];

export const navData = [
  {
    name: "Chicken Hyderabad (Bone)",
  },
  {
    name: "Chicken Andhra (Bone)",
  },
  {
    name: "Chicken Chat Pat",
  },
  {
    name: "Panjabi Chicken",
  },
  {
    name: "Chicken Kadai (Bone Less)",
  },
  {
    name: "Chicken Rogan Josh",
  },
  {
    name: "Chicken Seema (Bone)",
  },
  {
    name: "Chicken Kalli Mirchi",
  },
  {
    name: "Chicken Butter (Bone Less)",
  },
  {
    name: "Chicken Patiyala",
  },
  {
    name: "Egg Masala",
  },
  {
    name: "Chicken Andhra (Bone Less)",
  },
];
